name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: npm ci

    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  jest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: npm ci

    - name: Annotated Jest
      uses: rkusa/jest-action@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
